"""initial league schema

Revision ID: 9c8d7bdbecd3
Revises:
Create Date: 2026-10-02 17:54:42.933891

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c8d7bdbecd3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "sft",
                "main",
                "exploiter",
                "uploaded",
                "baseline",
                name="agentkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "pool",
            sa.Enum("training", "evaluation", name="agentpool", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("checkpoint_uri", sa.String(length=1024), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_agents_pool"), "agents", ["pool"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "sft",
                "self_play",
                "exploiter_training",
                "evaluation",
                name="jobkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                name="jobstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("opponent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "result",
            sa.Enum("win", "draw", "loss", name="matchresult", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "purpose",
            sa.Enum("training", "evaluation", name="matchpurpose", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("replay_uri", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("agent_id <> opponent_id", name="ck_matches_distinct_players"),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["opponent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_matches_agent_purpose", "matches", ["agent_id", "purpose"], unique=False)
    op.create_index(
        "ix_matches_opponent_purpose", "matches", ["opponent_id", "purpose"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_matches_opponent_purpose", table_name="matches")
    op.drop_index("ix_matches_agent_purpose", table_name="matches")
    op.drop_table("matches")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_agents_pool"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
